### ISSUE TITLE
Infinite loop zBorderSS

### ISSUE THREAD

**Issue by Delgon95** [BGSU-RNA/FR3D#10]
I encountered a problem while reading file 488D.pdb. It enters infinite loop in file zBorderSS at line 121 and newer leaves. Used zAddNTData to read file.

**Comment by clzirbel** [comment]
Hi,

I recently fixed a situation like this with a different file.  The 
problem was that one base was making two cWW basepairs (GC or AU or GU), 
and that got it stuck in a loop.  This was fixed by improving the 
program that checks for one base using the Watson-Crick edge more than 
once.  This was pushed to the dev branch, and now 488D loads without the 
infinite loop.  Hopefully this helps you, too.

Craig

______________________________________________________________________
*Craig L. Zirbel*
Professor and Graduate Coordinator
Department of Mathematics and Statistics
BGSU | Bowling Green State University
Bowling Green, OH 43403
+1-419-372-7466; zirbel@bgsu.edu <mailto:zirbel@bgsu.edu>
http://www-math.bgsu.edu/~zirbel <http://www-math.bgsu.edu/%7Ezirbel>
______________________________________________________________________

**Comment by Delgon95** [comment]
Hi,
Unfortunately I still have this problem even on dev branch. I tried octave and newest MatLab to be sure and it still locks in the same loop. I'm using 488D.pdb from http://www.rcsb.org and trying to read with "File = zAddNTData(pdb_id);"

Mchal

**Comment by clzirbel** [comment]
Oops, my fault, haven't updated dev recently.  Sorry about that. Lots to 
commit, I'll get working on it soon.

______________________________________________________________________
*Craig L. Zirbel*
Professor and Graduate Coordinator
Department of Mathematics and Statistics
BGSU | Bowling Green State University
Bowling Green, OH 43403
+1-419-372-7466; zirbel@bgsu.edu <mailto:zirbel@bgsu.edu>
http://www-math.bgsu.edu/~zirbel <http://www-math.bgsu.edu/%7Ezirbel>
______________________________________________________________________
